In [335]:
import numpy as np
import random

In [336]:
data = np.array([1,2,3])



In [337]:
matriks = np.zeros((6,6))

matriks = np.random.random((3, 4))
print(matriks)


[[0.10351097 0.68481421 0.10504712 0.24640746]
 [0.90490238 0.84771042 0.22113308 0.80534044]
 [0.01253842 0.58444101 0.58139995 0.72836633]]


In [338]:
array1 = np.array([1,2,3])
array2 = np.array([4,5,6])
array3 = np.array([7,8,9])

[NUMPY V STACK]

nilai ini dapat distack tetapi hasilnya berupa vertikal 

In [339]:
"""
[1,2,3]
[4,5,6]
[7,8,9]
"""

matriks = np.vstack([array1, array2, array3])
matriks

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

[NUMPY H STACK]

nilai ini dapat distack tetapi hasilnya berupa horizontal 

In [340]:
"""
[1,2,3]
[4,5,6]
[7,8,9]
"""

matriks = np.hstack([array1, array2, array3])
matriks

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

[NUMPY COLUMN STACK]

nilai ini dapat distack tetapi hasilnya berupa column 

In [341]:
"""
[1,2,3]
[4,5,6]
[7,8,9]
"""
matriks = np.column_stack([array1, array2, array3])
matriks

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

INTERSECTION & DIFFERENCE

In [342]:
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([5,6,7,8,9])

INTERSECTION
yakni hanya mendapatkan nilai yang  ada di antara array

In [343]:
"""
[1,2,3,4,5,6]
[5,6,7,8,9]
"""

matriks = np.intersect1d(arr1,arr2)
matriks

array([5, 6])

DIFFERENCE
yakni mengambil nilai hanya pada satu array saja tetapi tidak ada nilai yg diantara array

In [344]:
"""
[1,2,3,4,5,6]
[5,6,7,8,9]
"""

matriks = np.setdiff1d(arr1,arr2)
matriks2 = np.setdiff1d(arr2,arr1)

print("ini diff1d", matriks, "inidiff2", matriks2)


ini diff1d [1 2 3 4] inidiff2 [7 8 9]


ADDITION NUMPY

In [345]:
"""
[1,2,3]
[4,5,6]
[7,8,9]
"""

matriks = np.sum([array1, array2, array3])

matriks2 = np.sum([array1, array2, array3], axis=0)

matriks3 = np.sum([array1, array2, array3], axis=1)

array4 = np.array([10,11])

try : 
    matriks4 = np.sum([array1, array2, array3,array4])
    matriks4
except : 
    print("error")

print(matriks, matriks2, matriks3)

error
45 [12 15 18] [ 6 15 24]


LOCAL STORAGE NUMPY

In [346]:
"""
[1,2,3]
[4,5,6]
[7,8,9]
"""

save_matriks = np.save("test", array1)

load_matriks = np.load("test.npy")

print(save_matriks, load_matriks)

None [1 2 3]


LATIHAN DATA NUMPY

:))))))))))))))))))) MAMAH AKU TAKUT :))))))))))))))))))))))))))))

MISALKAN NIH YA GAME BURIQUE HARVEST MOON kan ada tuh inventory kan ya, misal kita buat array data dengan jumlah 4 x 4 atau persegi jadi total nya kan 16 item yang bisa dimasukin tuh, nah gimana ya KALO item ke-4 kita ganti terus nantinya item tersebut berisi 3 data , atau 1 item berisi 3. nah bentuk inventory nya gini

[
    item 1,item2,0,0
    0,item3,item4,0
    0,item5,0,0
    0,0,0,0

]

UNTUK BENTUKNYA TERSERAH MAU VERTIKAL HORIZONTAL BOLEH ATAU SEBALIKNYA ASAL SETIAP BARIS MINIMAL 2.

OUTPUT YANG DIINGINKAN ADALAH

[
    item 1,item2,0,0
    0,item3,item4,item4
    item4,item5,0,0
    0,0,0,0
]
PROSES WAJIB MENGGUNAKAN PRINSIP OOP 

In [347]:
class ParentInventory():
    def __init__(self, name, mat):
        self.name = name
        self.price = mat
     

    def get_name(self):
        return self.name

    def set_name(self, name):
        self.name = name
    def get_mat(self):
        return self.mat

    def set_mat(self, mat):
        self.mat = mat


In [348]:
class ChildInvent(ParentInventory) : 
    def __init__(self, name, mat):
        super().__init__(name, mat)
        self.name = name
    def matInvent(self) : 
        self.mat = np.zeros(4,4)
        return self.mat


In [349]:
obje1 = ChildInvent("child", np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]]))
obje1.get_name()

'child'