In [22]:
import numpy as np
import random

In [23]:
data = np.array([1,2,3])



In [25]:
matriks = np.zeros((6,6))

matriks = np.random.random((3, 4))
print(matriks)


[[0.2966542  0.7400755  0.09820143 0.44449428]
 [0.65664306 0.68115851 0.4659862  0.36169778]
 [0.86261639 0.25206283 0.62314741 0.03306798]]
